server:
  port: 9003
spring:
  boot:
    admin:
      url: http://localhost:9001
      username: admin
      password: passw0rd
      client:
        name: client-b
management:
  security:
    enabled: false
  context-path: /actuator