server:
  port: 9002
spring:
  boot:
    admin:
      url: http://localhost:9001
      username: admin
      password: passw0rd
      client.name: client-a
management:
  security:
    enabled: false
  context-path: /actuator
